### ISSUE TITLE
the dropdown for select2 is unuseable for edit_inlines when you use the javascript "add another"

### ISSUE THREAD

**Issue by lakinwecker** [theatlantic/django-select2-forms#27]
If you click "Add Another" to add another form and then try to use the select2 widget in that form, it doesn't work properly. The dropdown shows up at the top of the screen and as far as I can tell it's not functional.  I'm happy to look into this further if you can point me in the right direction.

**Comment by jfscyberpub** [comment]
I have the same bug. Any updates coming soon ?

**Comment by lakinwecker** [comment]
I had to work around it. I made a jquery callback that waited 200ms or so, and then re-instantiated the chosen element within the newly added formset.  It's a total hack, but it works. :(

**Comment by jfscyberpub** [comment]
Could you please share your hack ? Thank you :)

**Comment by lakinwecker** [comment]
@jfscyberpub - https://gist.github.com/lakinwecker/a1c4f9d512478d59dbe514a120e01204

**Comment by fdintino** [comment]
Sorry for the lack of recent updates to this project. I hope to give it more love sometime soon, but I can't make any promises. As noted in #33, your best bet is to use the `formset:added` event if you're using Django >= 1.9, since that will be more reliable than a timeout. For Django 1.8 you could also use [django-nested-admin](https://github.com/theatlantic/django-nested-admin), which has a [backport of the `formset:added` event](http://django-nested-admin.readthedocs.io/en/latest/customization.html#events), and can be used as a replacement for the standard django `ModelAdmin` even if you don't need the nested inline feature.

**Comment by jfscyberpub** [comment]
Thanks to both of you.
